### ISSUE TITLE
FEATURE REQUEST: Vehicle Location

### ISSUE THREAD

**Issue by glassbase** [samrum/OnStarJS#139]
The app can do it, so I am sure it can be reverse engineered into this. :)

thanks

**Comment by HeatfanJohn** [comment]
The key for this is to figure out how the app does this.  Perhaps running the app in the Android development environment virtual machine and then using something like Fiddler to capture all of the API calls using Fiddler's wildcard SSL certificates to allow decryption of HTTPS traffic.
