### ISSUE TITLE
New API keys?

### ISSUE THREAD

**Issue by Suisse00** [samrum/OnStarJS#17]
Hi!

I was poking on my side (on android) and end up finding your git (yeah!).
The clientId seems to have been updated, I now have OMB_CVY_AND_3Q0. (just replace AND with iOS)
Though I don't know if they increased the clientSecret length or if it is different per platform. (Length is 36 on my side),

**Comment by samrum** [comment]
Hmm, I'm not sure if the iOS client id is kept in sync with the Android one like that. It's possible that one is changed and released before the other.
When I was using the Android values before, the client secret was the same length as the iOS one (21 characters), so they may have diverged there. It's also possible the newer iOS client secret is longer.

I've generally just been pulling and updating the client id and secret when the old ones are deprecated and stop working which is usually every few months, so I don't know what the latest iOS values are.

**Comment by Suisse00** [comment]
This is was just a FYI just in case.

I thought the client id could have been updated because the 3 last characters are incremented sequentially (with some gap).
I take a chance about sharing the same keys between both os.
