### ISSUE TITLE
getAccountVehicles - Error: Request Failed with status 500 - Internal Server Error

### ISSUE THREAD

**Issue by bugs181** [samrum/OnStarJS#173]
Trying to follow the example. Double checked the credentials and everything is correct. But receiving the error.

Code:

```js
const OnStar = require("onstarjs")

const onStar = OnStar.create({
  deviceId: "...",
  vin: "...",
  username: "myemail@gmail.com",
  password: "password",
  onStarPin: "####",
})

async function main() {
  try {
    const vehicles = await onStar.getAccountVehicles()
    console.log(vehicles)

  } catch (err) {
    throw new Error(err)
  }
}
```

Other commands seem to work fine, such as:
- `await onStar.alert`
- `await onStar.start`
- `await onStar.cancelStart`

**Comment by samrum** [comment]
Usually 500 errors are triggered by an issue with the config values, but if the other commands are working I'm not sure what the problem could be. getAccountVehicles works for me, so it could just be an issue on their end with your account.
