### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by nodiaque** [samrum/OnStarJS#204]
Hello,

I'm trying to use onstar2mqtt and I'm getting error 500. The owner of the solution told me to post here. I'm from Quebec, Canada and I'm unsure if we're suppose to have a different API or not.

This is what the log file in the docker give me:
https://pastebin.com/pp1S889V

I've checked my pihole server when I open the MyChrevolet App for my bolt and saw it communicate on these domain (if that help anything):
generalmotorscorporation.sc.omtrdc.net
galileo-api.ext.gm.com
na-mobile-api.gm.com
apim.gm.com
www.chevrolet.com
omnibus.gm.com

This is the link to the issue I opened @ onstar2mqtt that sent me here:
https://github.com/michaelwoods/onstar2mqtt/issues/206

Thank you!

**Comment by samrum** [comment]
500 is usually indicative of a formatting error in your config.

In the past, people have confirmed that Canada works with the same API:
https://github.com/samrum/homebridge-onstar/issues/21
https://github.com/samrum/homebridge-onstar/issues/2

**Comment by nodiaque** [comment]
Hello, saw I never did a follow-up. I found out the issue. I was using my onstart account that doesn't own a car, only a family shared one. Turns out, it doesn't work with that account. Once I start using the car owner account, it start working. Thank you!

**Comment by mattdsteele** [comment]
Thanks for following up - I just ran into this same issue; I was trying to use a shared family account and was seeing a 500 error with payload `{"code":"ONS-107","description":"Invalid account"}`
