### ISSUE TITLE
Getting 401 Unauthorized

### ISSUE THREAD

**Issue by BennyDaBee** [samrum/OnStarJS#214]
Hello, 

starting yesterday or Wednesday, started getting 401 errors. The latest branch does not fix this.

**Comment by glassbase** [comment]
Related https://github.com/michaelwoods/onstar2mqtt/issues/243

**Comment by BennyDaBee** [comment]
> Perhaps this change has something to do with it? [6e159a5](https://github.com/samrum/OnStarJS/commit/6e159a523870323040c5018e68fdc30644abc8ce)
> 
> Unless I'm misunderstanding, perhaps that app secret is revoked / shouldn't be in source.
> 
> @samrum Perhaps you can provide further details on that change and what those values are used for?

As well, it was broken before I merged this into my current version. Something for sure changed on GMs end. Hopefully, Joel will be able to ping it down for us.

**Comment by Z1mDMan** [comment]
any update on this? how can I help (as a non-programmer but tech savvy)

**Comment by BennyDaBee** [comment]
@chakal I see you were trying to work on this. Did you have any luck?

**Comment by BennyDaBee** [comment]
@joelvandal not sure if this may help https://blog.sanghviharshit.com/reverse-engineering-private-api-ssl-pinning/

**Comment by BennyDaBee** [comment]
Testing on mine now @joelvandal

**Comment by BennyDaBee** [comment]
Still learning development myself, would that include the request diagnostics using api/v2?

**Comment by BennyDaBee** [comment]
Also @joelvandal is the appSecret still the same or has it changed?

**Comment by BennyDaBee** [comment]
Ok, how about the appId? Trying to track down why im still getting 401

**Comment by BennyDaBee** [comment]
`But if I check on my trace, I see :

/api/v1/account/vehicles/MYVIN/requests/start1603817341674601627557

So the "commands" was been renamed to "requests" and a number is append after the start parameter.`

Glossed over this. Wonder what the random number in full means.

**Comment by michaelwoods** [comment]
@joelvandal that seemed to do it. I disabled the token upgrade by default and I'm able to request diagnostics. PR incoming.

**Comment by BennyDaBee** [comment]
@michaelwoods @joelvandal Was able to confirm that lock/unlock/start/cancelStart all returned and completed as normal

**Comment by usmcfiredog** [comment]
Thank you all for the great work!
